@startuml
scale 1

class GreatWizard extends Wizard {
    -int gmp = 150
    ~GreatWizard(String name, int hp, int mp)

    ~<Override>void heal(Hero hero)
    ~void superHeal(Hero hero)
}

class Wizard {
    -String name
    -int hp
    -int mp = 100
    -Wand wand

    +Wizard(String name, int hp, int mp, Wand wand)
    +Wizard(String name, int hp, int mp)
    +void heal(Hero hero)
}


class PoisonSlime extends Slime {
    -int poisonCount = 5

    +PoisonSlime(String suffix)

    +<Override>void attack(Hero hero)
}

class Slime {
    -final String suffix
    -int hp = 100

    +Slime(String suffix)
    +void attack(Hero hero)
}

class Hero {
    -String name
    -int hp
    -int maxHp = 300

    ~Hero(String name, int hp)
    ~void attack()
}


@enduml