@startuml
scale 1.5

class SuperHero extends Hero implements Flyable {
    +void setFlying(bool flying)
    +boolean isFlying()
    +void attack()
    +void move(int sec)
}

class Hero implements Attackable, Moveable {
    -int hp
    -String name

    +void attack()
}

class Wizard

interface Attackable {
    void attack(Slime slime)
}

interface Moveable {
    void move(int sec)
}

interface Flyable {
    void setFlying(bool flying)
}

@enduml