@startuml
scale 0.7
abstract class Asset {
    - String name;
    + Asset(String name)
}


abstract class IntangibleAsset extends Asset {
    + IntangibleAsset(String name)
    }

abstract class TangibleAsset extends Asset implements Thing {
    - double weight;
    - String color;
    - int price;

    + TangibleAsset(String name, int price, String color)
        super(name);
    }

class Computer extends TangibleAsset {
        - String markerName;

        + Computer(String name, int price, String color, String markerName)




        + double weight()<<Override>>

        + void setweight(double weight)<<Override>>
        }

class Book extends TangibleAsset {
    - String isbn;


    + Book(String name, int price, String color, String isbn)

    + String getIsbn()

    + void setIsbn(String isbn)


    + double weight() <<Override>>


    + void setweight(double weight) <<Override>>
    }

class Patent extends IntangibleAsset {
    - String patentNum;

    + Patent(String name, String PatentNum)

    + String getPatentNum()

    + void setPatentNum(String patentNum)
}
@enduml