@startuml

interface brood {}

interface Entity {
    + int getHP()
    + int getArmor()
    + int getMaxHP()
    + int getPrice()

    + void setHP(int hp)
    + void setArmor(int armor)
    + void setMaxHP(int maxHP)
    + void setPrice()
}

interface MoveableEntity extends Entity {
    + int getSpeed()
    + void setSpeed(int speed)

    + void move()
}

interface Unit extends Entity {}

interface AttackableEntity extends Entity {
    + void attack(Entity target)
}

interface Bionic extends Unit, MoveableEntity {}

interface Mechanic extends Unit, MoveableEntity {}

interface MagicEntity extends Entity {
    + int getMP()
    + int getMaxMP()

    + void setMP(int mp)
    + void setMaxMP(int maxMP)
}

interface Structure extends Entity {}

interface Worker {
    + void mining()
}

interface RepairableEntity extends Entity {}

interface HealableEntity extends Entity {}

abstract class Terran implements brood {}

abstract class Protoss implements brood {
    - int currentShield
    - int maxShield
    - final double restoreShield

    + int getCurrentShield()
    + int getMaxShield()

    + void setCurrentShield(int currentShield)
    + void setMaxShield(int maxShield)
}

abstract class Zerg implements brood {
    - int restoreHP

    + int getRestoreHP()
}

class Marine extends Terran implements Bionic, AttackableEntity, HealableEntity {}

class Medic extends Terran implements Bionic, MagicEntity, HealableEntity {
    + void heal(HealableEntity target)
}

class Vulture extends Terran implements Mechanic, AttackableEntity, RepairableEntity {}

class Tank extends Terran implements Mechanic, AttackableEntity, RepairableEntity {}

class Scv extends Terran implements Mechanic, Bionic, Worker, AttackableEntity, RepairableEntity {
    + void repair(Repairable target)
}

class Zergling extends Zerg implements Bionic, Unit, AttackableEntity {}
class Hydra extends Zerg implements Bionic, Unit, AttackableEntity {}

class Zealot extends Protoss implements Bionic, Unit, AttackableEntity {}
class Dragun extends Protoss implements Mechanic, Unit, AttackableEntity {}

class UnitGroup {
    - Unit[] Units

    + void move()
    + void attack(Entity target)
}

@enduml
