@startuml
'https://plantuml.com/class-diagram

scale 2

class Book extends TangibleAsset {
    -String isbn
}

class Computer extends TangibleAsset  {
   -String makerName
}

abstract class TangibleAsset {
    -String name
    -int price
    -String color
}

interface Thing {
    double getWeight()
    void setWeight(double weight)
}

@enduml