@startuml
'https://plantuml.com/class-diagram

scale 1.5

class Book extends TangibleAsset {
    -String isbn
}

class Computer extends TangibleAsset  {
   -String makerName
}

abstract class TangibleAsset extends Asset {
    -String color
}

abstract class IntangibleAsset extends Asset

class Patent extends IntangibleAsset

interface Thing {
    double getWeight()
    void setWeight(double weight)
}

abstract class Asset {
    -String name
    -int price
}

@enduml